version: "3.8"
services:
  mongo:
    container_name: ds-mongo
    image: mongo:4.2.10-bionic
    command: --config /etc/mongo/mongod.conf --port ${MONGO_PORT:-27017}
    env_file: mongo.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-mongo}
    expose:
      - "${MONGO_CONTAINER_PORT:-27017}"
    ports:
      - "${MONGO_HOST_PORT:-27017}:${MONGO_CONTAINER_PORT:-27017}"
    volumes:
      - ./mongo/mongod.conf:/etc/mongo/mongod.conf
      - ./mongo/mongo-init:/docker-entrypoint-initdb.d

  mongo-express:
    depends_on:
      - mongo
    container_name: ds-mongo-express
    image: mongo-express:0.54.0
    env_file: mongo.env
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME:-admin}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-mongo}
      ME_CONFIG_MONGODB_PORT: ${MONGO_CONTAINER_PORT:-27017}
    ports:
      - "8081:8081"

# networks:

