version: "3.8"
services:
  mongo:
    # container_name: ds-mongo
    image: mongo:4.2.10-bionic
    command: --config /etc/mongo/mongod.conf --port ${MONGO_PORT:-27017}
    env_file: mongo.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-mongo}
    ports:
      - "${MONGO_HOST_PORT:-27017}:${MONGO_CONTAINER_PORT:-27017}"
    volumes:
      - ./mongo/mongod.conf:/etc/mongo/mongod.conf
      - ./mongo/mongo-init:/docker-entrypoint-initdb.d
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        # delay: 5s
        # max_attempts: 3
        # window: 60s
      placement:
        constraints:
          - "node.role==manager"

  mongo-express:
    depends_on:
      - mongo
    # container_name: ds-mongo-express
    image: mongo-express:0.54.0
    env_file: mongo.env
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME:-admin}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-mongo}
      ME_CONFIG_MONGODB_PORT: ${MONGO_CONTAINER_PORT:-27017}
    ports:
      - "8081:8081"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - "node.role==manager"

  storage-ftp:
    image: fauria/vsftpd:latest
    networks:
      - name_storage
    ports:
      - "20:20"
      - "21:21"
      - "21100-21110:21100-21110"
    environment:
      FTP_USER: ${FTP_USER:-ftpuser}
      FTP_PASS: ${FTP_PASS:-ftp-pass}
      PASV_MIN_PORT: "21100"
      PASV_MAX_PORT: "21110"
    deploy:
      mode: global
      placement:
        constraints:
          - "node.labels.storage_server==true"


networks:
  name_storage:
    driver: overlay
    attachable: false
    internal: true
