version: "3.8"
services:
  mongo:
    image: mongo:4.2.10-bionic
    command: --config /etc/mongo/mongod.conf --port ${MONGO_PORT:-27017}
    env_file: mongo.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-mongo}
    ports:
      - "${MONGO_HOST_PORT:-27017}:${MONGO_CONTAINER_PORT:-27017}"
    volumes:
      - ./mongo/mongod.conf:/etc/mongo/mongod.conf
      - ./mongo/mongo-init:/docker-entrypoint-initdb.d
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        # delay: 5s
        # max_attempts: 3
        # window: 60s
      placement:
        constraints:
          - "node.role==manager"

  mongo-express:
    depends_on:
      - mongo
    image: mongo-express:0.54.0
    env_file: mongo.env
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME:-admin}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-mongo}
      ME_CONFIG_MONGODB_PORT: ${MONGO_CONTAINER_PORT:-27017}
    ports:
      - "8081:8081"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - "node.role==manager"

  name-server:
    depends_on:
      - mongo
    image: sitiritis/ds-dfs-name-server:latest
    ports:
      - "8000:80"
    environment:
      MONGO_HOST: "${MONGO_HOST:-mongo}:${MONGO_CONTAINER_PORT:-27017}"
      MONGO_USER: ${MONGO_USER:-admin}
      MONGO_PASS: ${MONGO_PASS:-mongo}
      FTP_USER: ${FTP_USER:-ftpuser}
      FTP_PASS: ${FTP_PASS:-ftp-pass}
      # STORAGE_REQUEST_TIMEOUT: ${STORAGE_REQUEST_TIMEOUT:-2}
      STORAGE_SERVER_PORT: ${STORAGE_SERVER_PORT:-80}
    deploy:
      mode: replicated
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.role==manager"
      restart_policy:
        condition: on-failure

  storage-server-1:
    depends_on:
      - name-server
    image: sitiritis/ds-dfs-storage-server:latest
    ports:
      - target:    80
        published: 80
        protocol:  tcp
        mode:      host
      - target:    20
        published: 20
        protocol:  tcp
        mode:      host
      - target:    21
        published: 21
        protocol:  tcp
        mode:      host
      - target:    21100
        published: 21100
        protocol:  tcp
        mode:      host
      - target:    21101
        published: 21101
        protocol:  tcp
        mode:      host
      - target:    21102
        published: 21102
        protocol:  tcp
        mode:      host
    environment:
      FTP_USER: ${FTP_USER:-ftpuser}
      FTP_PASS: ${FTP_PASS:-ftp-pass}
      PASV_ENABLE: "YES"
      PASV_ADDRESS: ${SERVER_ADDR_1:?SERVER_ADDR_1 env is not set}
      PASV_ADDR_RESOLVE: ${PASV_ADDR_RESOLVE_1:-NO}
      NAME_SERVER_ADDRESS: ${NAME_SERVER_ADDRESS:-"http://name-server"}
      SERVER_ADDR: ${SERVER_ADDR_1}
      SERVER_PORT: ${SERVER_PORT_1:-80}
      PASV_MIN_PORT: 21100
      PASV_MAX_PORT: 21102
    deploy:
      mode: replicated
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.labels.storage_server==1"
      restart_policy:
        condition: on-failure
        delay: 5s

  storage-server-2:
    depends_on:
      - name-server
    image: sitiritis/ds-dfs-storage-server:latest
    ports:
      - target:    80
        published: 80
        protocol:  tcp
        mode:      host
      - target:    20
        published: 20
        protocol:  tcp
        mode:      host
      - target:    21
        published: 21
        protocol:  tcp
        mode:      host
      - target:    21100
        published: 21100
        protocol:  tcp
        mode:      host
      - target:    21101
        published: 21101
        protocol:  tcp
        mode:      host
      - target:    21102
        published: 21102
        protocol:  tcp
        mode:      host
    environment:
      FTP_USER: ${FTP_USER:-ftpuser}
      FTP_PASS: ${FTP_PASS:-ftp-pass}
      PASV_ENABLE: "YES"
      PASV_ADDRESS: ${SERVER_ADDR_2:?SERVER_ADDR_1 env is not set}
      PASV_ADDR_RESOLVE: ${PASV_ADDR_RESOLVE_2:-NO}
      NAME_SERVER_ADDRESS: ${NAME_SERVER_ADDRESS:-"http://name-server"}
      SERVER_ADDR: ${SERVER_ADDR_2}
      SERVER_PORT: ${SERVER_PORT_2:-80}
      PASV_MIN_PORT: 21100
      PASV_MAX_PORT: 21102
    deploy:
      mode: replicated
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.labels.storage_server==2"
      restart_policy:
        condition: on-failure
        delay: 5s
